- name: vars from prompt
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: "Enter the username"
      private: false

    - name: password
      prompt: "Enter the password"
      private: true

  tasks:
    - name: print the username and password
      ansible.builtin.debug:
        msg: "username is {{ username }}, password is {{ password }}"
